package com.example.lazyco.entities.User;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum UserMessage implements MessageCodes {
  USER_NOT_FOUND("USER_MODULES.USER_NOT_FOUND"),
  ROLE_NOT_FOUND("USER_MODULES.ROLE_NOT_FOUND"),
  PASSWORD_CANNOT_BE_EMPTY("USER_MODULES.PASSWORD_CANNOT_BE_EMPTY"),
  INCORRECT_PASSWORD("USER_MODULES.INCORRECT_PASSWORD"),
  USER_ID_OR_PASSWORD_INCORRECT("USER_MODULES.USER_ID_OR_PASSWORD_INCORRECT"),
  ACCOUNT_DISABLED("USER_MODULES.ACCOUNT_DISABLED"),
  ACCOUNT_LOCKED("USER_MODULES.ACCOUNT_LOCKED"),
  PASSWORD_EXPIRED("USER_MODULES.PASSWORD_EXPIRED"),
  USER_NOT_AUTHORIZED("USER_MODULES.USER_NOT_AUTHORIZED"),
  ROLE_NOT_SELECTED("USER_MODULES.ROLE_NOT_SELECTED"),
  PASSWORD_RESET_INITIATED("USER_MODULES.PASSWORD_RESET_INITIATED"),
  INVALID_RESET_TOKEN("USER_MODULES.INVALID_RESET_TOKEN"),
  PASSWORD_RESET_SUCCESS("USER_MODULES.PASSWORD_RESET_SUCCESS"),

  LOGOUT_SUCCESS("USER_MODULES.LOGOUT_SUCCESS");
  private final String value;

  UserMessage(String value) {
    this.value = value;
  }
}
