package com.example.lazyco.core.Exceptions;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum CommonMessage implements MessageCodes {
  CUSTOM_MESSAGE("COMMON_MODULES.CUSTOM_MESSAGE"),
  APPLICATION_ERROR("COMMON_MODULES.APPLICATION_ERROR"),
  ATOMIC_OPERATION_ERROR("COMMON_MODULES.ATOMIC_OPERATION_ERROR"),
  NON_ATOMIC_OPERATION_ERROR("COMMON_MODULES.NON_ATOMIC_OPERATION_ERROR"),
  OBJECT_REQUIRED("COMMON_MODULES.OBJECT_REQUIRED"),
  OBJECT_NOT_FOUND("COMMON_MODULES.OBJECT_NOT_FOUND"),
  ID_REQUIRED("COMMON_MODULES.ID_REQUIRED"),
  INTERNET_IS_SLOW("COMMON_MODULES.INTERNET_IS_SLOW"),
  FIELD_MISSING("COMMON_MODULES.FIELD_MISSING"),
  REFERENCE_NOT_FOUND("COMMON_MODULES.REFERENCE_NOT_FOUND"),
  REFERENCE_IN_USE("COMMON_MODULES.REFERENCE_IN_USE"),
  REFERENCE_ERROR("COMMON_MODULES.REFERENCE_ERROR"),
  DUPLICATE_RECORD("COMMON_MODULES.DUPLICATE_RECORD"),
  DUPLICATE_FIELD("COMMON_MODULES.DUPLICATE_FIELD"),
  CODE_ALREADY_EXISTS("COMMON_MODULES.CODE_ALREADY_EXISTS"),
  ERROR_VALIDATING_CODE("COMMON_MODULES.ERROR_VALIDATING_CODE"),
  CODE_REQUIRED("COMMON_MODULES.CODE_REQUIRED"),
  ERROR_VALIDATING_NAME("COMMON_MODULES.ERROR_VALIDATING_NAME"),
  NAME_REQUIRED("COMMON_MODULES.NAME_REQUIRED"),
  ;
  private final String value;

  CommonMessage(String value) {
    this.value = value;
  }
}
