package com.example.lazyco.entities.ProgramCurriculum;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum ProgramCurriculumMessage implements MessageCodes {
  PROGRAM_CURRICULUM_CODE_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_CODE_REQUIRED"),
  PROGRAM_CURRICULUM_NAME_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_NAME_REQUIRED"),
  DUPLICATE_PROGRAM_CURRICULUM_NAME("PROGRAM_CURRICULUM.DUPLICATE_PROGRAM_CURRICULUM_NAME"),
  PROGRAM_CURRICULUM_START_DATE_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_START_DATE_REQUIRED"),
  PROGRAM_CURRICULUM_END_DATE_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_END_DATE_REQUIRED"),
  PROGRAM_CURRICULUM_ADMISSION_CAPACITY_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_ADMISSION_CAPACITY_REQUIRED"),
  PROGRAM_CURRICULUM_MIN_CREDIT_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_MIN_CREDIT_REQUIRED"),
  PROGRAM_CURRICULUM_MAX_CREDIT_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_MAX_CREDIT_REQUIRED"),
  PROGRAM_CURRICULUM_CREDIT_VALIDATION("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_CREDIT_VALIDATION"),
  PROGRAM_CURRICULUM_ACADEMIC_YEAR_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_ACADEMIC_YEAR_REQUIRED"),
  PROGRAM_CURRICULUM_TERM_SYSTEM_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_TERM_SYSTEM_REQUIRED"),
  PROGRAM_CURRICULUM_PROGRAM_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_PROGRAM_REQUIRED"),
  PROGRAM_CURRICULUM_TERM_CYCLE_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_TERM_CYCLE_REQUIRED"),
  PROGRAM_CURRICULUM_INVALID_DATES("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_INVALID_DATES"),
  PROGRAM_CURRICULUM_INVALID_CONVICTION_DATE(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_INVALID_CONVICTION_DATE"),
  PROGRAM_CURRICULUM_ACADEMIC_PROGRAM_NOT_FOUND(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_ACADEMIC_PROGRAM_NOT_FOUND"),
  PROGRAM_CURRICULUM_PROGRAM_TERM_SYSTEM_NOT_ASSOCIATED_WITH_PROGRAM(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_PROGRAM_TERM_SYSTEM_NOT_ASSOCIATED_WITH_PROGRAM"),
  ;
  private final String value;

  ProgramCurriculumMessage(String value) {
    this.value = value;
  }
}
