package com.example.lazyco.entities.ProgramCurriculum;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum ProgramCurriculumMessage implements MessageCodes {
  PROGRAM_CURRICULUM_CODE_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_CODE_REQUIRED"),
  PROGRAM_CURRICULUM_NAME_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_NAME_REQUIRED"),
  PROGRAM_CURRICULUM_START_DATE_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_START_DATE_REQUIRED"),
  PROGRAM_CURRICULUM_END_DATE_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_END_DATE_REQUIRED"),
  PROGRAM_CURRICULUM_ADMISSION_CAPACITY_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_ADMISSION_CAPACITY_REQUIRED"),
  PROGRAM_CURRICULUM_MIN_CREDIT_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_MIN_CREDIT_REQUIRED"),
  PROGRAM_CURRICULUM_MAX_CREDIT_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_MAX_CREDIT_REQUIRED"),
  PROGRAM_CURRICULUM_ACADEMIC_YEAR_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_ACADEMIC_YEAR_REQUIRED"),
  PROGRAM_CURRICULUM_TERM_SYSTEM_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_TERM_SYSTEM_REQUIRED"),
  PROGRAM_CURRICULUM_PROGRAM_REQUIRED("PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_PROGRAM_REQUIRED"),
  PROGRAM_CURRICULUM_TERM_CYCLE_REQUIRED(
      "PROGRAM_CURRICULUM.PROGRAM_CURRICULUM_TERM_CYCLE_REQUIRED"),
  DUPLICATE_PROGRAM_CURRICULUM_NAME("PROGRAM_CURRICULUM.DUPLICATE_PROGRAM_CURRICULUM_NAME"),
  ;

  private final String value;

  ProgramCurriculumMessage(String value) {
    this.value = value;
  }
}
