package com.example.lazyco.entities.ApplicationForm;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum ApplicationFormMessage implements MessageCodes {
  ADMISSION_OFFER_REQUIRED("APPLICATION_FORM.ADMISSION_OFFER_REQUIRED"),
  APPLICATION_NUMBER_REQUIRED("APPLICATION_FORM.APPLICATION_NUMBER_REQUIRED"),
  APPLICATION_NUMBER_ALREADY_EXISTS("APPLICATION_FORM.APPLICATION_NUMBER_ALREADY_EXISTS"),
  FIRST_NAME_REQUIRED("APPLICATION_FORM.FIRST_NAME_REQUIRED"),
  EMAIL_REQUIRED("APPLICATION_FORM.EMAIL_REQUIRED"),
  EMAIL_INVALID("APPLICATION_FORM.EMAIL_INVALID"),
  PHONE_NUMBER_INVALID("APPLICATION_FORM.PHONE_NUMBER_INVALID"),
  PHONE_NUMBER_REQUIRED("APPLICATION_FORM.PHONE_NUMBER_REQUIRED"),
  CUSTOM_FIELD_REQUIRED("APPLICATION_FORM.CUSTOM_FIELD_REQUIRED"),
  CUSTOM_FIELD_INVALID_VALUE("APPLICATION_FORM.CUSTOM_FIELD_INVALID_VALUE"),
  APPLICATION_FORM_NOT_FOUND("APPLICATION_FORM.APPLICATION_FORM_NOT_FOUND"),
  APPLICATION_FORM_ALREADY_ENROLLED("APPLICATION_FORM.APPLICATION_FORM_ALREADY_ENROLLED"),
  APPLICATION_FORM_NOT_ENROLLED("APPLICATION_FORM.APPLICATION_FORM_NOT_ENROLLED"),
  APPLICATION_FORM_HAS_LINKED_DATA("APPLICATION_FORM.APPLICATION_FORM_HAS_LINKED_DATA"),
  APPLICATION_FORM_ALREADY_EXISTS("APPLICATION_FORM.APPLICATION_FORM_ALREADY_EXISTS"),
  ;
  private final String value;

  ApplicationFormMessage(String value) {
    this.value = value;
  }
}
