package com.example.lazyco.entities.ProgramCycle;

import com.example.lazyco.core.Messages.MessageCodes;
import lombok.Getter;

@Getter
public enum ProgramCycleMessage implements MessageCodes {
  PROGRAM_CYCLE_CODE_REQUIRED("PROGRAM_CYCLE.PROGRAM_CYCLE_CODE_REQUIRED"),
  PROGRAM_CYCLE_DATES_REQUIRED("PROGRAM_CYCLE.PROGRAM_CYCLE_DATES_REQUIRED"),
  PROGRAM_CYCLE_INVALID_DATES("PROGRAM_CYCLE.PROGRAM_CYCLE_INVALID_DATES"),
  PROGRAM_CYCLE_CREDITS_REQUIRED("PROGRAM_CYCLE.PROGRAM_CYCLE_CREDITS_REQUIRED"),
  PROGRAM_CYCLE_INVALID_CREDITS("PROGRAM_CYCLE.PROGRAM_CYCLE_INVALID_CREDITS"),
  PROGRAM_CYCLE_CREDIT_VALIDATION("PROGRAM_CYCLE.PROGRAM_CYCLE_CREDIT_VALIDATION"),
  PROGRAM_CYCLE_REGISTRATION_DATE_REQUIRED(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_REGISTRATION_DATE_REQUIRED"),
  PROGRAM_CYCLE_INVALID_REGISTRATION_DATE("PROGRAM_CYCLE.PROGRAM_CYCLE_INVALID_REGISTRATION_DATE"),
  PROGRAM_CYCLE_WITHDRAWN_DEADLINE_DATE_REQUIRED(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_WITHDRAWN_DEADLINE_DATE_REQUIRED"),
  PROGRAM_CYCLE_INVALID_WITHDRAWN_DEADLINE_DATE(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_INVALID_WITHDRAWN_DEADLINE_DATE"),
  PROGRAM_CYCLE_GRADES_SUBMISSION_DEADLINE_DATE_REQUIRED(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_GRADES_SUBMISSION_DEADLINE_DATE_REQUIRED"),
  PROGRAM_CYCLE_INVALID_GRADES_SUBMISSION_DEADLINE_DATE(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_INVALID_GRADES_SUBMISSION_DEADLINE_DATE"),
  PROGRAM_CYCLE_TERM_CYCLE_REQUIRED("PROGRAM_CYCLE.PROGRAM_CYCLE_TERM_CYCLE_REQUIRED"),
  PROGRAM_CYCLE_PROGRAM_CURRICULUM_REQUIRED(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_PROGRAM_CURRICULUM_REQUIRED"),
  PROGRAM_CYCLE_PROGRAM_TERM_MASTER_REQUIRED(
      "PROGRAM_CYCLE.PROGRAM_CYCLE_PROGRAM_TERM_MASTER_REQUIRED"),
  ;
  private final String value;

  ProgramCycleMessage(String value) {
    this.value = value;
  }
}
