package com.example.lazyco.backend.core.ConfigurationMaster.SystemSettingsMetaData;

import lombok.Getter;

@Getter
public enum SystemSettingsKeys {
  SYSTEM_TIMEZONE("SYSTEM_TIMEZONE"),
  CLIENT_TIMEZONE("CLIENT_TIMEZONE"),
  MONGO_DB_NAME("MONGO_DB_NAME"),
  MONGO_DB_URL("MONGO_DB_URL"),
  REDIS_CACHE_URL("REDIS_CACHE_URL"),
  REDIS_CACHE_PORT("REDIS_CACHE_PORT"),
  REDIS_CACHE_EXPIRATION("REDIS_CACHE_EXPIRATION"),
  REDIS_CACHE_ENABLE("REDIS_CACHE_ENABLE"),
  APP_URL("APP_URL"),
  SMTP_EMAIL_CLIENT("SMTP_CLIENT"),
  SMTP_USERNAME("SMTP_USERNAME"),
  SMTP_PASSWORD("SMTP_PASSWORD"),
  SMTP_HOST("SMTP_HOST"),
  SMTP_HOST_USER_ID("SMTP_HOST_USER_ID"),
  SMTP_HOST_PASSWORD("SMTP_HOST_PASSWORD"),
  SMTP_PORT("SMTP_PORT"),
  SMTP_SSL_PROTOCOL("SMTP_SSL_PROTOCOL"),
  SMTP_DEBUG("SMTP_DEBUG"),
  ROLE_ADMIN("ROLE_ADMIN"),
  SECURITY_ROLE("SECURITY_ROLE"),
  SECURITY_ROLE_CLIENT("SECURITY_ROLE_CLIENT"),
  ;
  private final String value;

  SystemSettingsKeys(String value) {
    this.value = value;
  }
}
